### ISSUE TITLE
How to obtain SshError

### ISSUE THREAD

**Issue by iBernd81** [1148118271/ssh-rs#66]
Sending commands returns a `SshResult<()>` object. Calling `get_result()` afterwards will obtain the result of the command. Fine and working so far.

But what is the best way to check for an error or better obtain the error message?

In `error.rs` I can see the following mapping: `pub type SshResult<I> = Result<I, SshError>;`

Thank you for every answer or suggestion.

**Comment by HsuJv** [comment]
Hi @iBernd81 

If you're looking for all branches to match the `SshResult`, here are the enum defines 
https://github.com/1148118271/ssh-rs/blob/0e85a0455e3d8defe142c146fdeed7d5de745d9b/src/error.rs#L50-L57
And an example is here
https://github.com/1148118271/ssh-rs/blob/0e85a0455e3d8defe142c146fdeed7d5de745d9b/examples/shell/src/main.rs#L32-L41
You can use some `match e.kind()` tests to get all of them.

And a refactor of the errors to redefine them to `anyhow` errors is in progress, which may make it easier to use.

BRs.

**Comment by HsuJv** [comment]
BTW, can I do a simple survey here?
Is it okay for you that the next release of this crate will change from sync APIs to async APIs?

**Comment by iBernd81** [comment]
At first @HsuJv thank you very much for your answer. I think I can improve my code a little bit now.

But it seems, secondly, that your crate is not reacting on wrong commands or commands not running. For example the exec command "somethingwrong" is resulting in okay and this is exactly the point I want to capture.

**Comment by HsuJv** [comment]
Hi @iBernd81 Thank you for your feedback. Maybe it's better to split the async behaviours from this crate.

And regarding the issue you said

> the exec command "something wrong" is resulting in okay

is a known issue currently. It was because we forget to handle the extended data back from the server, and what's more, the `SshResult` is more focused on the protocol errors itself. The command error should be returned in another way.


If you specify the crate
```Toml
ssh-rs = { git="https://github.com/1148118271/ssh-rs", branch = "main" }
```
in your `Cargo.toml`, the latest code can get the error message back from the server now (Also the `get_result` call). But still, we do not have an API to test if the exec was successful or failed.

I was spending time on another crate recently and will attempt to give a solution to this issue ASAP. Also, it's welcome to issue your PR if you've got a brilliant idea.

BRs.

**Comment by HsuJv** [comment]
BTW, the latest code has an API change that `timeout` starts using `std::time::Duration` instead of `usize`.

**Comment by iBernd81** [comment]
Great! After switching the crate's origin I can see the sever's command output. You can close this issue now and I will have a look on your next versions of `ssh-rs`.
