### ISSUE TITLE
ssh -rs crashed on Zero lenght version information

### ISSUE THREAD

**Issue by Paulo-21** [1148118271/ssh-rs#85]
Hello,
I encountered an error when running ssh -rs in several threads.
I'm trying to connect to a real ssh server, which may be behind a firewall or a specific security system.

![panic](https://github.com/1148118271/ssh-rs/assets/34631206/29ce25cf-4103-430c-b529-2f611c304234)

**Comment by HsuJv** [comment]
Hi

Could you help use `python` or any other script to connect a `TCP` connection to your `ssh server ip:port`, and call `read` on this connection once connected?

Looks like the server doesn't respond their ssh version to us, the protocol version exchange (https://www.rfc-editor.org/rfc/rfc4253#section-4.2) fails and panic with some careless code

BRs.

**Comment by Paulo-21** [comment]
I can add that there is "portsentry -atcp" activated on the server and the openssh version is 7.6p1.
It would be difficult to do that because i have a limited access to it.
Can it be possible to return an error like "Inapropriate_ssh_response_from_server" rather than panic ?

**Comment by HsuJv** [comment]
Yes, you're right, it shall throw errors instead of panic.

Since you mentioned `portsentry` is running. I guess it might require us to send out the version negotiation first.
I'll also make some changes to see if this can fix the issue.

Could you please use `ssh-rs = { git = "https://github.com/HsuJv/ssh-rs.git", branch = "patch_85" }` to help verify this issue?

BRs

**Comment by Paulo-21** [comment]
Hey,
I have tested and it work properly.
Thank you for you responsiveness and you kindness as always ;)
